In [2]:
# list comprehension
print([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10])
print([i for i in range(10)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
# functions

def square(x):
    return x**2

def sum(a, b):
    return a + b

In [4]:
b = [i**2 for i in range(10)] # list comprehension
print(b)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [6]:
print(list(map(square, b)))  # map

[0, 1, 16, 81, 256, 625, 1296, 2401, 4096, 6561]


In [8]:
squared = []                # for loop
for elem in b:
    squared.append(elem**2)
print(squared)
    

[0, 1, 16, 81, 256, 625, 1296, 2401, 4096, 6561]


In [9]:
import numpy as np
import pandas as pd

In [59]:
# Creating ndarrays
list1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1.__class__)

# implicit data type
np1 = np.array(list1)
print(np1)

# explicitly specify the data type
np2 = np.array(list1, dtype="float64")

# data types:
# int, uint, float
# precision 16 (half precision), 32 (single precision), 64(double precision)

# mixed data types type casted to highest order
np3 = np.array([1, 2.])
print("np3 dtype:", np3.dtype)

print("\n", np2)
print(np1.__class__)
print(type(np1))
print("np1:", np1)
print(len(np1))
print(np1.shape)
print(np1.dtype)
print(len(np1[0]))

<class 'list'>
[[1 2 3 4]
 [5 6 7 8]]
np3 dtype: float64

 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
np1: [[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64
4


In [60]:
# useful initialization functions
print(np.zeros(10))
print(np.zeros((3, 5)))
print(np.ones((2, 4)))
print(np.arange(15).reshape(3, 5))
print(np.identity(4))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
import random
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [71]:
print(np.random.randn(5))  # normal random numbers 0 mean 1 std dev.
print(np.random.random(5)) # uniformly random numbers between 0 and 1

[-1.53828964 -1.15432165 -0.93808309  1.31948978  0.54889709]
[0.50843045 0.73477478 0.08218927 0.63106606 0.29890736]


In [103]:
# create ndarray with random numbers
import random
random.seed(9)
choices = [1, 3, 5, 7, 9]
print(np.array([random.choice(choices) for i in range(5)]))
print(np.array([random.choice(range(15)) for i in range(10)]))

[7 9 5 5 3]
[ 2 13 10  0  5  8  7 14  9  1]


In [97]:
# Using a seed (reproducing results)
random.seed(2)
print(random.randint(1, 5))

1


### Selecting Columns and Rows

In [40]:
arr = np.arange(10)
print(arr)
arr[5]

[0 1 2 3 4 5 6 7 8 9]


5

In [54]:
print(arr[5:8]) 

[5 6 7]


In [17]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [42]:
# Aliasing
a = [1, 2, 3, 4, 5]
b = a
a[0] = 2
print(b)
b = a[:]
#b = a.copy()
b[1] = 42
print(a)
print(b)

[2, 2, 3, 4, 5]
[2, 2, 3, 4, 5]
[2, 42, 3, 4, 5]


In [106]:
arr = np.arange(15).reshape(3, 5)
print(arr[1])     # select 1st row (index 0)
print(arr[1, 2])  # select 2nd row (index 1), 3rd column (index 2)

[5 6 7 8 9]
7


In [11]:
print(arr)
print(arr[:2])  # till row 2
print(arr[1:])  # from row 1 onwards

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
print(arr[:, :2]) # all rows and first 2 columns
print(arr[:2, :2])
print(arr[0,1]) # access single element in a 2D array

[[ 0  1]
 [ 5  6]
 [10 11]]
[[0 1]
 [5 6]]
1


In [44]:
# Transpose
t = np.arange(15).reshape(3, 5)
print(t)
print(t.shape)
tt = t.T
print(tt)
print(tt.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(5, 3)


In [45]:
# dot product and matrix multiplication
a = [1, 2, 3]
b = [2, 3, 4]
print(np.dot(a, b))  # dot product of two vectors
print(np.dot(t, tt)) # matrix multiplication

20
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [111]:
# Universal functions (Unary)
arr = np.arange(1,10)
print("sqrt:", np.sqrt(arr))
print("exp:", np.exp(arr))      # e^x 
print("exp2:", np.exp2(arr))    # 2^x
print("square:", np.square(arr))
print("log10:", np.log10(arr))  # log base 10
print("log:", np.log(arr))      # natural log (base e)

sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
exp: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
exp2: [  2.   4.   8.  16.  32.  64. 128. 256. 512.]
square: [ 1  4  9 16 25 36 49 64 81]
log10: [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [51]:
np.arange(10)
np.arange(2, 8)
np.arange(2, 10, 2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [116]:
# Universal function (Binary)
a = np.arange(1, 11) # [1, 2, ... , 10]
b = np.arange(11, 21) # [11, 12, ... , 20]
print(np.add(a, b))
print(np.subtract(b, a))
print(np.multiply(a, b))
print(np.divide(b, a))
print(np.greater_equal(b, a))

[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[11  6  4  3  3  2  2  2  2  2]
[ True  True  True  True  True  True  True  True  True  True]


In [117]:
x1 = [4, 2, 1]
x2 = [2, 2, 2]
print(np.greater_equal(x1, x2))
print(np.mod(x1, x2))

[ True  True False]
[0 0 1]


### Logical Operations

In [61]:
x1 = [True, False, True, False]
x2 = [True, True, False, False]
print(np.logical_and(x1, x2))
print(np.logical_or(x1, x2))
print(np.logical_xor(x1,x2))
print(np.logical_not(x1))

[ True False False False]
[ True  True  True False]
[False  True  True False]
[False  True False  True]


### Math and Stats built-in functions

In [112]:
# math and stat functions
arr = np.array([[0, 1, 2], [3, 2, 5], [6, 7, 2]])
print(arr.mean())
print(arr.sum())
print(arr.std())

3.111111111111111
28
2.23330569358242


In [115]:
# Combining Arrays
x = np.arange(10)
y = np.arange(10, 20)
z = np.arange(20, 30)
zp = np.array(list(zip(x, y, z))) # python 3 creates zip object
print(zp)
print(zp[:,0])

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]
[0 1 2 3 4 5 6 7 8 9]


In [119]:
a = np.array([[1, 2, 3], [2, 3, 4]])
z = np.zeros((2, 2))
np.append(a, z, axis=1) # column bind

array([[1., 2., 3., 0., 0.],
       [2., 3., 4., 0., 0.]])

In [118]:
z2 = np.zeros((2, 3))
np.append(a, z2, axis=0) # row bind

array([[1., 2., 3.],
       [2., 3., 4.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# subsetting / filtering
d = np.array([
        [1, 2, 3],
        [1, 3, 4],
        [2, 2, 3],
        [2, 3, 4]
    ])
print(d[d[:, 1] == 3])

[[1 3 4]
 [2 3 4]]


In [77]:
x = np.arange(100)
print(np.mean(x))
print(np.median(x))
print(np.std(x))

49.5
49.5
28.8660700477


### Concatenating Numpy Arrays

In [51]:
np.random.randn(10) * 10 + 30

array([ 52.17998961,  20.79225344,  35.18201411,  20.30773848,
        35.71043343,  28.70134289,  36.87380472,  27.96734337,
        27.94656163,  13.58017602])